### ISSUE TITLE
comparar método mais rapido

### ISSUE THREAD

**Issue by gavital** [victorperin/APS-03#15]
E se a gente criasse mais um arquivo onde comparasse e mostrasse qual dos métodos é mais rápido, o que menos fez trocas/comparações? Não sei se o Victor pensou nisso e já tava fazendo.. Mas se não, poderíamos cogitar essa ideia né?!
Até porque a gente vai ter que colocar isso na parte escrita, já aproveita e coloca no programa já

**Comment by victorperin** [comment]
Blz isso é necessário mesmo.
Mas pensei em colocar no System.out.print(). O que vocês acham?

**Comment by victorperin** [comment]
Podemos também colocar isso em um arquivo chamado: resumo.txt

**Comment by victorperin** [comment]
Vou ver se ainda consigo fazer isso hoje ainda...

**Comment by victorperin** [comment]
Vai demorar mais tempo do que eu estava pensando...

**Comment by victorperin** [comment]
Parece que já está rodando corretamente, preciso só que o pessoal teste o branch `metodos-as-object` para ver se está tudo certo

**Comment by gavital** [comment]
Vo testar aqui victor, ja te falo se deu algo errado =)

**Comment by gavital** [comment]
achei um erro. Não criei a pasta imagens, ai digitei o desktop como destino... Tá organizando por tamanho, mas por nome da exception no main.. 
NullPointerException
at Sorts.checarSeArquivoEhAntes(Sorts.java:192)
at Sorts.selectionSort(Sorts.java:66)
at Sorts.sort(Sorts.java:34)
at Main.salvarArquivo(Main.java:99)
at Main.main(Main.java:73)

**Comment by gavital** [comment]
deu mesma coisa se eu pedir pra ordenar os arquivos da pasta APS lol

**Comment by gavital** [comment]
Aparentemente ta dando erro sempre que tem uma pasta dentro da pasta destino...

Ah, ta configurado pra parar o programa caso o usuário não digite nada na hora de colocar a pasta e ele simplesmente aperte enter?

**Comment by victorperin** [comment]
Valeu gabi, pode ser então algum erro na classe imagem. Vou dar uma verificada
pelo PC e já te aviso...

On qua, mai 13, 2015 at 10:47 AM, Gabriela Vital < notifications@github.com [notifications@github.com] > wrote:
Aparentemente ta dando erro sempre que tem uma pasta dentro da pasta destino...

—
Reply to this email directly or view it on GitHub
[https://github.com/victorperin/APS-03/issues/15#issuecomment-101668902] .[https://github.com/notifications/beacon/AFk4aedmvcf2Rnv1aS1c-oygo_QDcLueks5oI01YgaJpZM4EU77C.gif]

**Comment by gavital** [comment]
de nada! :D 

sobre aquela ideia de organizar todas as pastas que encontrar, qq vc acha de dar essa opção pro usuário?
tipo, nesse caso que tinha pastas dentro de pastas, aparece uma mensagem perguntando se o usuário quer que organize os arquivos dentro daquela pasta, manja?!
pa as vezes o cara quer organizar só aqueles arquivos, e não as outras pastas..

**Comment by victorperin** [comment]
Boa ideia, vou aproveitar esse erro pra ver se já é possível fazer isso...

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.26&pv=5.1.1]

On qua, mai 13, 2015 at 11:12 AM, Gabriela Vital < notifications@github.com [notifications@github.com] > wrote:
sobre aquela ideia de organizar todas as pastas que encontrar, qq vc acha de dar
essa opção pro usuário?
tipo, nesse caso que tinha pastas dentro de pastas, aparece uma mensagem
perguntando se o usuário quer que organize os arquivos dentro daquela pasta,
manja?!
pa as vezes o cara quer organizar só aqueles arquivos, e não as outras pastas..

—
Reply to this email directly or view it on GitHub
[https://github.com/victorperin/APS-03/issues/15#issuecomment-101677650] .[https://github.com/notifications/beacon/AFk4aSR6fgrK24QT9EsfDhsMnnHxd47Yks5oI1NggaJpZM4EU77C.gif]

**Comment by victorperin** [comment]
``` shell
Tempo gasto Arquivos Desordenados: 0,572396100 segundos.
Quantidade de imagens na pasta "imagens/": 1744

Tempo gasto selection: 0,039810147 segundos.
Tempo gasto shell: 0,004188235 segundos.
Tempo gasto bubble: 0,000407458 segundos.
Tempo gasto insertion: 0,025392896 segundos.
Tempo gasto anchor: 0,060911097 segundos.

OrdenaÃ§Ãµes por nome do arquivo:
Exception in thread "main" java.lang.NullPointerException
        at Sorts.checarSeArquivoEhAntes(Sorts.java:192)
        at Sorts.selectionSort(Sorts.java:66)
        at Sorts.sort(Sorts.java:34)
        at Main.salvarArquivo(Main.java:95)
        at Main.main(Main.java:69)
```

Percebi que o erro ocorre na classe dos métodos, apenas quando se organiza por nome do arquivo...

**Comment by gavital** [comment]
beleza, acho que podemos aproveitar esse erro pra fazer isso sim.
Isso! só na ordenação por nome dos arquivos e quando tem pasta + arquivos

**Comment by victorperin** [comment]
Carregar subpastas ainda não está sendo feito de forma recursiva, carrega subpastas mas não carrega subpastas dessas subpastas... :shipit:

**Comment by victorperin** [comment]
Beleza, subpastas já estão funcionando, agora é só voltar ao foco do issue...
Comparar o método mais rápido.
Consigo fazer isso agora e criar um arquivo resumo, onde vai mostar o mais rápido e ainda por cima, vai conter mais informações sobre cada sort.

**Comment by victorperin** [comment]
Linkando pull request #19

**Comment by victorperin** [comment]
Finalizado, por favor, só teste para ver se tudo está correto...
