### ISSUE TITLE
Shellsort

### ISSUE THREAD

**Issue by gavital** [victorperin/APS-03#4]
Victor, ainda ta dando erro nas linhas 43 e 45.. fala que o lado esquerdo de uma atribuição precisa ser uma variável..
Como faz pra selecionar aquele determinado nó na lista sem usar o set? pq acho que tem que colocar algo desse tipo: imagens[ j ].set(imagens.get( j - gap ))
sei lá..

ps: tentei colocar assim e agora java aponta:
Multiple markers at this line
- The left-hand side of an assignment must be a variable
- The type of the expression must be an array type but it resolved to ArrayList<Imagem>

**Comment by victorperin** [comment]
Linkando pull request #3
